name: Test

on:
  workflow_run:
    workflows:
      - Preflight
    types:
      - completed
jobs:
  test-job:
    name: Test Step 12
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: $
      - run: git branch
      - run: env